using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Interpreter_lib.Parser;

public enum ERule
{
    ROOT, 

    STATEMENT, 
    
    WHILE_LOOP, DO_WHILE_LOOP, REPEAT_UNTIL_LOOP,
    FOR_LOOP, FOR_LOOP_STEP,
    IF_STATEMENT, ELSE_STATEMENT,
    PRINT, SUBSEQUENT_PRINT,
    READ, SUBSEQUENT_READ,

    ASSIGNMENT,

    EXPRESSION,

    LOGICAL_OR, SUBSEQUENT_LOGICAL_OR,
    LOGICAL_AND, SUBSEQUENT_LOGICAL_AND,
    BITWISE_OR, SUBSEQUENT_BITWISE_OR,
    BITWISE_XOR, SUBSEQUENT_BITWISE_XOR,
    BITWISE_AND, SUBSEQUENT_BITWISE_AND,
    NOT_EQUAL, SUBSEQUENT_NOT_EQUAL,
    EQUAL, SUBSEQUENT_EQUAL,
    GREATER_THAN_EQUAL, SUBSEQUENT_GREATER_THAN_EQUAL,
    GREATER_THAN, SUBSEQUENT_GREATER_THAN,
    LESS_THAN_EQUAL, SUBSEQUENT_LESS_THAN_EQUAL,
    LESS_THAN, SUBSEQUENT_LESS_THAN,
    BITWISE_RIGHT_SHIFT, SUBSEQUENT_BITWISE_RIGHT_SHIFT,
    BITWISE_LEFT_SHIFT, SUBSEQUENT_BITWISE_LEFT_SHIFT,
    SUM, SUBSEQUENT_SUM,
    SUBTRACT, SUBSEQUENT_SUBTRACT,
    MULTIPLY, SUBSEQUENT_MULTIPLY,
    DIVIDE, SUBSEQUENT_DIVIDE,
    MODULUS, SUBSEQUENT_MODULUS,
    POWER, SUBSEQUENT_POWER,
    
    UNARY, 
    UNARY_MINUS, UNARY_PLUS, UNARY_NOT, UNARY_BITWISE_NOT,

    PRIMARY,
    
    FLOOR,
    GROUP,
}
